#!/usr/bin/env python
from __future__ import division, print_function
import argparse
import sys

import numpy as np

from pynamd import TitratableSystemSet


parser = argparse.ArgumentParser()
# Required arguments
parser.add_argument('cphlog', type=str, nargs='*', default=[],
    help='Any number of namdcph cphlog files'
)
required = parser.add_argument_group('required non-positional arguments')
required.add_argument('--json', type=str, nargs='*', default=[],
    help='cph JSON file(s) used during the simulation'
)
# Options for selecting residues
selection = parser.add_argument_group('residue selection options')
selection.add_argument('--segresids', type=str, nargs='*', default=[],
    help=('Select specific residues for analysis with the format'
          '<segid>:<resid>')
)
selection.add_argument('--notsegresids', type=str, nargs='*', default=[],
    help=('Exclude specific residues from analysis with the format'
          '<segid>:<resid>')
)
selection.add_argument('--resnames', type=str, nargs='*', default=[],
    help='Select specific residues for analysis by residue name'
)
selection.add_argument('--notresnames', type=str, nargs='*', default=[],
    help='Exclude specific residues from analysis by residue name'
)
# Options for reading data
data = parser.add_argument_group('data reading options')
data.add_argument('--start', type=int, default=0,
    help='First step to consider when subsampling'
)
data.add_argument('--stop', type=int, default=None,
    help='Last step to consider when subsampling'
)
data.add_argument('--step', type=int, default=None,
    help='Interval at which to subsample'
)
# Options for types of analysis
analysis = parser.add_argument_group('analysis options')
analysis.add_argument('--micro', action='store_true',
    help='Analyze microscopic states separately'
)
analysis.add_argument('--noequiv', action='store_true',
    help='Analyze a priori equivalent microscopic states separately'
)

analysis.add_argument('--wald', '--naive', action='store_true',
    help='Use the (naive) Wald method for population estimation'
)
analysis.add_argument('--yates', action='store_true',
    help='Use the Yates method for population estimation'
)
analysis.add_argument('--agresti_coull', action='store_true',
    help='Use the Agresti-Coull method for population estimation'
)
analysis.add_argument('-z', type=float, default=1.0,
    help=('Confidence parameter for the estimator.'
          ' z = z_a/2 is the 100(1 - a/2) percentile of the standard normal'
         )
)

analysis.add_argument('--eps1', type=float, default=1e-4,
    help='During fitting, ignore values below eps1 or above 1 - eps1'
)
analysis.add_argument('--eps2', type=float, default=1e-5,
    help='During fitting, ignore values with errors below eps2'
)

# currently the default
# analysis.add_arugment('--msmle_uwham', action='store_true')
analysis.add_argument('--msmle_opt', type=str, default='trust-ncg',
    help='Scipy minimizer to use for MSMLE'
)
analysis.add_argument('--msmle_guess', type=str, default=None,
    help='File to read intial MSMLE grand potential from.'
)
analysis.add_argument('--msmle_rstrt', type=str, default=None,
    help='File to write MSMLE grand potential to.'
)
analysis.add_argument('--msmle_cov', action='store_true', default=False,
    help='Compute the Hill fit by computing the MSMLE covariance (EXPERIMENTAL)')
analysis.add_argument('--hilldecomp', type=str, default=None, 
    help='Perform MSMLE Hill decomposition (EXPERIMENTAL!) and output to this file.'
)
analysis.add_argument('--bootstrap', type=int, default=0,
    help='Number of bootstrap trials for error estimation'
)

if len(sys.argv) < 2:
    parser.print_help()
    sys.exit()
args = parser.parse_args()
if len(args.json) == 0:
    print('Must specify at least one cph JSON config file.')
    sys.exit()
if args.stop < 0 or args.stop < args.start:
    args.stop = None

args.method = 'uwham'
args.method = ('wald' if args.wald else args.method)
args.method = ('yates' if args.yates else args.method)
args.method = ('agresti-coull' if args.agresti_coull else args.method)

args.micro = (True if args.noequiv else args.micro)

#
# Read in, subsample, and sort all of the data.
#
tset = TitratableSystemSet.from_cphlogs(args.cphlog, args.json,
                                        args.start, args.stop, args.step)
pHs, npHs, nsamples = tset.pHs, tset.numpHs, tset.nsamples

#
# Print a quick report regarding what was read.
#
print('# Read %d cphlog files (%d pH values)'%(len(args.cphlog), npHs))
print('# %5s %8s'%('pH', 'nsamples'))
for pH, n in zip(pHs, nsamples):
    print('# %5.2f %8d'%(pH, n))

#
# Each value in tcurve_dict is an ndarray with one or more titration curves.
# The key for each value is the <segid:resid:resname> identifier for that
# residue.
#
kopts = {'method': args.msmle_opt}

if args.msmle_guess is not None:
    data = np.loadtxt(str(args.msmle_guess)).T
    if data[0].size != pHs.size:
        print('Mismatch in number of pH values in msmle_guess (%d != %d)'%(data[0].size, pHs.size)) 
        sys.exit()
    if np.any(data[0] - pHs != 0.0):
        print('Mismatch in pH values in msmle_guess')
        sys.exit()
    kopts['f_guess'] = data[1]    

tcurve_dict = tset.compute_titration_curves(
    args.segresids, args.notsegresids, args.resnames, args.notresnames,
    args.micro, args.noequiv, args.method, args.z, **kopts
)

def space_columns(colcnt):
    """Add whitespace so that lines wrap at 80 characters. This alignment
    assumes a 5 char label and then 4 15 character columns.
    """
    colcnt += 1
    spacer = ''
    if colcnt == 4:
        spacer = ' '*20
        colcnt = 0
    return colcnt, spacer

#
# Print a header with residue information (<segid:resid:resname>).
#
print('# state population method: %s'%args.method)
colcnt = 0
header = '#     '
for segresidname, tcurve in tcurve_dict.iteritems(): 
    colcnt, spacer = space_columns(colcnt)
    header += ' %14s'%(segresidname) + spacer
    for i in xrange(tcurve[0].shape[0] - 1):
        colcnt, spacer = space_columns(colcnt) 
        header += ' '*14 + spacer
print(header.rstrip())

#
# Print the titration curves per state.
#
for i, pH in enumerate(pHs):
    colcnt = 0
    line = '%6.3f'%pH
    for (tcs, tc_errs) in tcurve_dict.itervalues():
        for p, perr in zip(tcs[:, i], tc_errs[:, i]):
            colcnt, spacer = space_columns(colcnt)
            line += ' %7.4f %6.4f'%(p, perr) + spacer
    print(line.rstrip())

opts = [args.micro, args.noequiv, args.method]
dohilldecomp = (args.hilldecomp is not None)
if args.msmle_cov:
    if args.wald or args.yates or args.agresti_coull:
        print('# MSMLE covariance only available with pure MSMLE')
        sys.exit()
    pKa_method = 'MSMLE-%s covariance'%args.method.upper()
    opts.extend([dohilldecomp, args.bootstrap])
    compute_Hill = tset.compute_Hill_msmle
else:
    if dohilldecomp:
        print('# Hill decomposition is only available with MSMLE covariance')
        sys.exit()
    pKa_method = 'non-linear regression'
    opts.extend([args.z, args.eps1, args.eps2])
    compute_Hill = tset.compute_Hill_fit

#
# Hill analysis (may be time consuming)
#
print('# pKa and Hill coefficient method: %s'%pKa_method)
colcnt = 0
line1 = '#pKa  '
line2 = '#hill '
hilloutput = []
hilllabels = []
for segresidname, tcurve in tcurve_dict.iteritems():
    try:
        # Don't waste time if the curve is totally flat.
        if np.all(tcurve[0] < 0.0001) or np.all(tcurve[0] > 0.9999):
            raise ValueError
        pKas, hillcoeffs, pKa_errs, hillcoeff_errs =\
                compute_Hill(segresidname, *opts, **kopts)

        for pKa, hill, pKa_err, hill_err in\
                zip(pKas, hillcoeffs, pKa_errs, hillcoeff_errs):
            colcnt, spacer = space_columns(colcnt)
            line1 += ' %7.4f %6.4f'%(pKa, pKa_err) + spacer
            if not dohilldecomp:
                line2 += ' %7.4f %6.4f'%(hill, hill_err) + spacer
            else:
                _hill = hill.sum()
                _hill_err = np.sqrt(hill_err**2).sum()
                line2 += ' %7.4f %6.4f'%(_hill, _hill_err) + spacer
                hilloutput.append(hill)
                hilllabels.append(segresidname)
    except ValueError:
        nstates = tcurve_dict[segresidname][1].shape[0]
        for i in xrange(nstates):
            colcnt, spacer = space_columns(colcnt)
            line1 += ' '*13 + '--' + spacer
            line2 += ' '*13 + '--' + spacer
print(line1.rstrip())
print(line2.rstrip())
print("# nan/-- indicates the pKa is probably outside the given pH range")
print("# -- may also indicate that this micro/noequiv is not implemented")
if dohilldecomp:
    hilloutfile = open(str(args.hilldecomp), 'w')
    hilloutfile.write('%-14s'%'residues')
    for label in hilllabels:
        hilloutfile.write(' %-13s'%label)
    hilloutfile.write('\n')
    x = np.asarray(hilloutput).T
    for segresid, resname, hillcoeffs in zip(tset.segresids(), tset.resnames(), x):
        hilloutfile.write('%-14s'%(':'.join([segresid, resname])))
        for hillcoeff in hillcoeffs:
#            hillcoeff = (hillcoeff if hillcoeff != 1.0 else 0.0)
            hilloutfile.write(' % 13.4f'%hillcoeff)
        hilloutfile.write('\n')
    hilloutfile.close()

if args.msmle_rstrt is not None:
    outfile = open(str(args.msmle_rstrt), 'w')
    for pH, f in zip(pHs, tset._msmle.f):
        outfile.write('%5.2f %e\n'%(pH, f))
    outfile.close()
